const constants = {
  // 都道府県
  prefecturesCodeList: [
    {
      label: "北海道・東北",
      options: [
        { value: "1", label: "北海道" },
        { value: "2", label: "青森県" },
        { value: "3", label: "岩手県" },
        { value: "4", label: "宮城県" },
        { value: "5", label: "秋田県" },
        { value: "6", label: "山形県" },
        { value: "7", label: "福島県" }
      ]
    },
    {
      label: "関東",
      options: [
        { value: "8", label: "茨城県" },
        { value: "9", label: "栃木県" },
        { value: "10", label: "群馬県" },
        { value: "11", label: "埼玉県" },
        { value: "12", label: "千葉県" },
        { value: "13", label: "東京都" },
        { value: "14", label: "神奈川県" }
      ]
    },
    {
      label: "甲信・北陸",
      options: [
        { value: "15", label: "新潟県" },
        { value: "16", label: "富山県" },
        { value: "17", label: "石川県" },
        { value: "18", label: "福井県" },
        { value: "19", label: "山梨県" },
        { value: "20", label: "長野県" }
      ]
    },
    {
      label: "東海",
      options: [
        { value: "21", label: "岐阜県" },
        { value: "22", label: "静岡県" },
        { value: "23", label: "愛知県" },
        { value: "24", label: "三重県" }
      ]
    },
    {
      label: "近畿",
      options: [
        { value: "25", label: "滋賀県" },
        { value: "26", label: "京都府" },
        { value: "27", label: "大阪府" },
        { value: "28", label: "兵庫県" },
        { value: "29", label: "奈良県" },
        { value: "30", label: "和歌山県" }
      ]
    },
    {
      label: "中国",
      options: [
        { value: "31", label: "鳥取県" },
        { value: "32", label: "島根県" },
        { value: "33", label: "岡山県" },
        { value: "34", label: "広島県" },
        { value: "35", label: "山口県" }
      ]
    },
    {
      label: "四国",
      options: [
        { value: "36", label: "徳島県" },
        { value: "37", label: "香川県" },
        { value: "38", label: "愛媛県" },
        { value: "39", label: "高知県" }
      ]
    },
    {
      label: "九州・沖縄",
      options: [
        { value: "40", label: "福岡県" },
        { value: "41", label: "佐賀県" },
        { value: "42", label: "長崎県" },
        { value: "43", label: "熊本県" },
        { value: "44", label: "大分県" },
        { value: "45", label: "宮崎県" },
        { value: "46", label: "鹿児島県" },
        { value: "47", label: "沖縄県" }
      ]
    }
  ]
};

const country = [
  { store_number: "KOR", store_nm: "韓国"},
  { store_number: "TWN", store_nm: "台湾"},
  { store_number: "HKG", store_nm: "香港"},
  { store_number: "VNM", store_nm: "ベトナム"},
  { store_number: "THA", store_nm: "タイ"},
  { store_number: "SGP", store_nm: "シンガポール"},
  { store_number: "MYS", store_nm: "マレーシア"},
  { store_number: "PHL", store_nm: "フィリピン"},
  { store_number: "IDN", store_nm: "インドネシア"},
  { store_number: "KHM", store_nm: "カンボジア"},
  { store_number: "LAO", store_nm: "ラオス"},
  { store_number: "MMR", store_nm: "ミャンマー"},
  { store_number: "IND", store_nm: "インド"},
  { store_number: "PAK", store_nm: "パキスタン"},
  { store_number: "LKA", store_nm: "スリランカ"},
  { store_number: "MDV", store_nm: "モルディブ"},
  { store_number: "BGD", store_nm: "バングラデシュ"},
  { store_number: "TLS", store_nm: "東ティモール"},
  { store_number: "MAC", store_nm: "マカオ"},
  { store_number: "AFG", store_nm: "アフガニスタン"},
  { store_number: "NPL", store_nm: "ネパール"},
  { store_number: "BTN", store_nm: "ブータン"},
  { store_number: "CHN", store_nm: "中国"},
  { store_number: "PRK", store_nm: "朝鮮民主主義人民共和国"},
  { store_number: "MNG", store_nm: "モンゴル"},
  { store_number: "BRN", store_nm: "ブルネイ"},
  { store_number: "BHR", store_nm: "バーレーン"},
  { store_number: "IRN", store_nm: "イラン"},
  { store_number: "IRQ", store_nm: "イラク"},
  { store_number: "SAU", store_nm: "サウジアラビア"},
  { store_number: "KWT", store_nm: "クウェート"},
  { store_number: "QAT", store_nm: "カタール"},
  { store_number: "OMN", store_nm: "オマーン"},
  { store_number: "YEM", store_nm: "イエメン"},
  { store_number: "ISR", store_nm: "イスラエル"},
  { store_number: "JOR", store_nm: "ヨルダン"},
  { store_number: "SYR", store_nm: "シリア"},
  { store_number: "LBN", store_nm: "レバノン"},
  { store_number: "ARE", store_nm: "アラブ首長国連邦"},
  { store_number: "LBY", store_nm: "リビア"},
  { store_number: "EGY", store_nm: "エジプト"},
  { store_number: "SDN", store_nm: "スーダン"},
  { store_number: "SOM", store_nm: "ソマリア"},
  { store_number: "TKL", store_nm: "トケラウ"},
  { store_number: "MAR", store_nm: "モロッコ"},
  { store_number: "DZA", store_nm: "アルジェリア"},
  { store_number: "TUN", store_nm: "チュニジア"},
  { store_number: "MRT", store_nm: "モーリタニア"},
  { store_number: "SEN", store_nm: "セネガル"},
  { store_number: "GMB", store_nm: "ガンビア"},
  { store_number: "GIN", store_nm: "ギニア"},
  { store_number: "SLE", store_nm: "シエラレオネ"},
  { store_number: "LBR", store_nm: "リベリア"},
  { store_number: "CIV", store_nm: "コートジボワール"},
  { store_number: "GHA", store_nm: "ガーナ"},
  { store_number: "TGO", store_nm: "トーゴ"},
  { store_number: "MLI", store_nm: "マリ"},
  { store_number: "NGA", store_nm: "ナイジェリア"},
  { store_number: "NER", store_nm: "ニジェール"},
  { store_number: "RWA", store_nm: "ルワンダ"},
  { store_number: "CMR", store_nm: "カメルーン"},
  { store_number: "TCD", store_nm: "チャド"},
  { store_number: "CAF", store_nm: "中央アフリカ"},
  { store_number: "GNQ", store_nm: "赤道ギニア"},
  { store_number: "GAB", store_nm: "ガボン"},
  { store_number: "COD", store_nm: "コンゴ民主共和国"},
  { store_number: "COG", store_nm: "コンゴ共和国"},
  { store_number: "BDI", store_nm: "ブルンジ"},
  { store_number: "AGO", store_nm: "アンゴラ"},
  { store_number: "KEN", store_nm: "ケニア"},
  { store_number: "UGA", store_nm: "ウガンダ"},
  { store_number: "TZA", store_nm: "タンザニア"},
  { store_number: "MOZ", store_nm: "モザンビーク"},
  { store_number: "MDG", store_nm: "マダガスカル"},
  { store_number: "MUS", store_nm: "モーリシャス"},
  { store_number: "ZAF", store_nm: "南アフリカ共和国"},
  { store_number: "LSO", store_nm: "レソト"},
  { store_number: "MWI", store_nm: "マラウイ"},
  { store_number: "ZMB", store_nm: "ザンビア"},
  { store_number: "SWZ", store_nm: "エスワティニ"},
  { store_number: "ETH", store_nm: "エチオピア"},
  { store_number: "ZWE", store_nm: "ジンバブエ"},
  { store_number: "BWA", store_nm: "ボツワナ"},
  { store_number: "ERI", store_nm: "エリトリア"},
  { store_number: "CPV", store_nm: "カーボベルデ"},
  { store_number: "GNB", store_nm: "ギニアビサウ"},
  { store_number: "COM", store_nm: "コモロ"},
  { store_number: "STP", store_nm: "サントメ・プリンシペ"},
  { store_number: "DJI", store_nm: "ジブチ"},
  { store_number: "SYC", store_nm: "セーシェル"},
  { store_number: "SHN", store_nm: "セントヘレナ・アセンションおよびトリスタンダクーニャ"},
  { store_number: "NAM", store_nm: "ナミビア"},
  { store_number: "BFA", store_nm: "ブルキナファソ"},
  { store_number: "BEN", store_nm: "ベナン"},
  { store_number: "AUT", store_nm: "オーストリア"},
  { store_number: "BEL", store_nm: "ベルギー"},
  { store_number: "DNK", store_nm: "デンマーク"},
  { store_number: "FIN", store_nm: "フィンランド"},
  { store_number: "NOR", store_nm: "ノルウェー"},
  { store_number: "FRA", store_nm: "フランス"},
  { store_number: "DEU", store_nm: "ドイツ"},
  { store_number: "ITA", store_nm: "イタリア"},
  { store_number: "LUX", store_nm: "ルクセンブルク"},
  { store_number: "NLD", store_nm: "オランダ"},
  { store_number: "ESP", store_nm: "スペイン"},
  { store_number: "SWE", store_nm: "スウェーデン"},
  { store_number: "CHE", store_nm: "スイス"},
  { store_number: "GBR", store_nm: "英国"},
  { store_number: "AND", store_nm: "アンドラ"},
  { store_number: "CYP", store_nm: "キプロス"},
  { store_number: "GIB", store_nm: "ジブラルタル"},
  { store_number: "GRC", store_nm: "ギリシャ"},
  { store_number: "TUR", store_nm: "トルコ"},
  { store_number: "ISL", store_nm: "アイスランド"},
  { store_number: "IRL", store_nm: "アイルランド"},
  { store_number: "LIE", store_nm: "リヒテンシュタイン"},
  { store_number: "MLT", store_nm: "マルタ"},
  { store_number: "MCO", store_nm: "モナコ"},
  { store_number: "PRT", store_nm: "ポルトガル"},
  { store_number: "VAT", store_nm: "バチカン"},
  { store_number: "GRL", store_nm: "グリーンランド"},
  { store_number: "HRV", store_nm: "クロアチア"},
  { store_number: "SMR", store_nm: "サンマリノ"},
  { store_number: "SVN", store_nm: "スロベニア"},
  { store_number: "SRB", store_nm: "セルビア"},
  { store_number: "MNE", store_nm: "モンテネグロ"},
  { store_number: "FRO", store_nm: "フェロー諸島"},
  { store_number: "BIH", store_nm: "ボスニア・ヘルツェゴビナ"},
  { store_number: "IMN", store_nm: "マン島"},
  { store_number: "ALB", store_nm: "アルバニア"},
  { store_number: "BGR", store_nm: "ブルガリア"},
  { store_number: "CZE", store_nm: "チェコ"},
  { store_number: "HUN", store_nm: "ハンガリー"},
  { store_number: "POL", store_nm: "ポーランド"},
  { store_number: "ROU", store_nm: "ルーマニア"},
  { store_number: "RUS", store_nm: "ロシア"},
  { store_number: "EST", store_nm: "エストニア"},
  { store_number: "LVA", store_nm: "ラトビア"},
  { store_number: "LTU", store_nm: "リトアニア"},
  { store_number: "UKR", store_nm: "ウクライナ"},
  { store_number: "SVK", store_nm: "スロバキア"},
  { store_number: "BLR", store_nm: "ベラルーシ"},
  { store_number: "MDA", store_nm: "モルドバ"},
  { store_number: "AZE", store_nm: "アゼルバイジャン"},
  { store_number: "ARM", store_nm: "アルメニア"},
  { store_number: "UZB", store_nm: "ウズベキスタン"},
  { store_number: "KAZ", store_nm: "カザフスタン"},
  { store_number: "KGZ", store_nm: "キルギス"},
  { store_number: "GEO", store_nm: "グルジア"},
  { store_number: "TJK", store_nm: "タジキスタン"},
  { store_number: "TKM", store_nm: "トルクメニスタン"},
  { store_number: "CAN", store_nm: "カナダ"},
  { store_number: "USA", store_nm: "米国"},
  { store_number: "PAN", store_nm: "パナマ"},
  { store_number: "BMU", store_nm: "バミューダ諸島"},
  { store_number: "BHS", store_nm: "バハマ"},
  { store_number: "JAM", store_nm: "ジャマイカ"},
  { store_number: "BRB", store_nm: "バルバドス"},
  { store_number: "TTO", store_nm: "トリニダード・トバゴ"},
  { store_number: "CUB", store_nm: "キューバ"},
  { store_number: "HTI", store_nm: "ハイチ"},
  { store_number: "DOM", store_nm: "ドミニカ共和国"},
  { store_number: "PRI", store_nm: "プエルトリコ"},
  { store_number: "VGB", store_nm: "イギリス領ヴァージン諸島"},
  { store_number: "CYM", store_nm: "ケイマン諸島"},
  { store_number: "ABW", store_nm: "アルバ"},
  { store_number: "GRD", store_nm: "グレナダ"},
  { store_number: "VCT", store_nm: "セントビンセント・グレナディーン"},
  { store_number: "LCA", store_nm: "セントルシア"},
  { store_number: "TCA", store_nm: "タークス・カイコス諸島"},
  { store_number: "IOT", store_nm: "イギリス領インド洋地域"},
  { store_number: "ARG", store_nm: "アルゼンチン"},
  { store_number: "BOL", store_nm: "ボリビア"},
  { store_number: "BRA", store_nm: "ブラジル"},
  { store_number: "HND", store_nm: "ホンジュラス"},
  { store_number: "GUY", store_nm: "ガイアナ"},
  { store_number: "CHL", store_nm: "チリ"},
  { store_number: "COL", store_nm: "コロンビア"},
  { store_number: "CRI", store_nm: "コスタリカ"},
  { store_number: "ECU", store_nm: "エクアドル"},
  { store_number: "SLV", store_nm: "エルサルバドル"},
  { store_number: "GUF", store_nm: "フランス領ギアナ"},
  { store_number: "GTM", store_nm: "グアテマラ"},
  { store_number: "MEX", store_nm: "メキシコ"},
  { store_number: "NIC", store_nm: "ニカラグア"},
  { store_number: "PRY", store_nm: "パラグアイ"},
  { store_number: "PER", store_nm: "ペルー"},
  { store_number: "URY", store_nm: "ウルグアイ"},
  { store_number: "VEN", store_nm: "ベネズエラ"},
  { store_number: "AUS", store_nm: "オーストラリア"},
  { store_number: "NZL", store_nm: "ニュージーランド"},
  { store_number: "PNG", store_nm: "パプアニューギニア"},
  { store_number: "WSM", store_nm: "サモア"},
  { store_number: "FJI", store_nm: "フィジー"},
  { store_number: "SLB", store_nm: "ソロモン諸島"},
  { store_number: "TON", store_nm: "トンガ"},
  { store_number: "NRU", store_nm: "ナウル"},
  { store_number: "NCL", store_nm: "ニューカレドニア"},
  { store_number: "MHL", store_nm: "マーシャル諸島"},
  { store_number: "GUM", store_nm: "グアム"},
  { store_number: "KIR", store_nm: "キリバス"},
  { store_number: "TUV", store_nm: "ツバル"},
  { store_number: "VUT", store_nm: "バヌアツ"},
  { store_number: "PLW", store_nm: "パラオ"},
  { store_number: "FSM", store_nm: "ミクロネシア連邦"},
  { store_number: "WLF", store_nm: "ウォリス・フツナ"},
  { store_number: "PYF", store_nm: "フランス領ポリネシア"},
  { store_number: "AIA", store_nm: "アンギラ"},
  { store_number: "ALA", store_nm: "オーランド諸島"},
  { store_number: "ASM", store_nm: "アメリカ領サモア"},
  { store_number: "ATA", store_nm: "南極"},
  { store_number: "ATF", store_nm: "フランス領南方・南極地域"},
  { store_number: "ATG", store_nm: "アンティグア・バーブーダ"},
  { store_number: "BES", store_nm: "ボネール、シント・ユースタティウスおよびサバ"},
  { store_number: "BLM", store_nm: "サン・バルテルミー"},
  { store_number: "BLZ", store_nm: "ベリーズ"},
  { store_number: "BVT", store_nm: "ブーベ島"},
  { store_number: "CCK", store_nm: "ココス諸島"},
  { store_number: "COK", store_nm: "クック諸島"},
  { store_number: "CUW", store_nm: "キュラソー"},
  { store_number: "CXR", store_nm: "クリスマス島"},
  { store_number: "DMA", store_nm: "ドミニカ国"},
  { store_number: "ESH", store_nm: "西サハラ"},
  { store_number: "FLK", store_nm: "フォークランド諸島"},
  { store_number: "GGY", store_nm: "ガーンジー"},
  { store_number: "GLP", store_nm: "グアドループ"},
  { store_number: "HMD", store_nm: "ハード島・マクドナルド諸島"},
  { store_number: "JEY", store_nm: "ジャージー"},
  { store_number: "KNA", store_nm: "セントキッツ・ネイビス"},
  { store_number: "MAF", store_nm: "サン・マルタン"},
  { store_number: "MKD", store_nm: "マケドニア"},
  { store_number: "MNP", store_nm: "北マリアナ諸島"},
  { store_number: "MSR", store_nm: "モントセラト"},
  { store_number: "MTQ", store_nm: "マルティニーク"},
  { store_number: "MYT", store_nm: "マヨット"},
  { store_number: "NFK", store_nm: "ノーフォーク島"},
  { store_number: "NIU", store_nm: "ニウエ"},
  { store_number: "PCN", store_nm: "ピトケアン諸島"},
  { store_number: "PSE", store_nm: "パレスチナ"},
  { store_number: "REU", store_nm: "レユニオン"},
  { store_number: "SGS", store_nm: "南ジョージア・南サンドウィッチ諸島"},
  { store_number: "SJM", store_nm: "スヴァールバル諸島・ヤンマイエン島"},
  { store_number: "SPM", store_nm: "サンピエール島・ミクロン島"},
  { store_number: "SSD", store_nm: "南スーダン共和国"},
  { store_number: "SUR", store_nm: "スリナム"},
  { store_number: "SXM", store_nm: "シント・マールテン"},
  { store_number: "UMI", store_nm: "合衆国領有小離島"},
  { store_number: "VIR", store_nm: "アメリカ領ヴァージン諸島"},
  { store_number: "ZZZ", store_nm: "朝鮮"},
  
];

export  {
  constants,
  country
};
